import type { Label } from "../data-type"

export const initialLabels: Label[] = [
  {
    id: "1",
    name: "Groceries",
    color: "bg-cyan-500",
    numberOfTransactions: 32,
    lastApplied: "7 days ago",
    created: "Mar 18",
  },
  {
    id: "2",
    name: "Restaurant",
    color: "bg-red-500",
    numberOfTransactions: 191,
    lastApplied: "1 day ago",
    created: "Feb 2024",
  },
  {
    id: "3",
    name: "Transport",
    color: "bg-gray-400",
    numberOfTransactions: 8,
    lastApplied: "9 days ago",
    created: "Sep 11",
  },
  {
    id: "4",
    name: "Entertainment",
    color: "bg-yellow-500",
    numberOfTransactions: 9,
    lastApplied: "17 days ago",
    created: "Mar 17",
  },
  {
    id: "5",
    name: "Health",
    color: "bg-purple-500",
    numberOfTransactions: 54,
    lastApplied: "9 days ago",
    created: "Feb 2024",
  },
  {
    id: "6",
    name: "Shopping",
    color: "bg-amber-700",
    numberOfTransactions: 31,
    lastApplied: "21 hours ago",
    created: "Mar 18",
  },
  {
    id: "7",
    name: "Bills",
    color: "bg-blue-600",
    numberOfTransactions: 3,
    lastApplied: "9 months ago",
    created: "Mar 2024",
  },
  {
    id: "8",
    name: "Other",
    color: "bg-green-600",
    numberOfTransactions: 7,
    lastApplied: "3 months ago",
    created: "Mar 2024",
  },
  {
    id: "9",
    name: "Savings",
    color: "bg-gray-400",
    numberOfTransactions: 8,
    lastApplied: "16 days ago",
    created: "Mar 2024",
  },
  {
    id: "10",
    name: "Investments",
    color: "bg-gray-400",
    numberOfTransactions: 3,
    lastApplied: "7 weeks ago",
    created: "Mar 2024",
  },
]
